DO NOTE THAT THIS PROGRAM PRINTS THE SERIES OF FIBONACCI NUMBERS THAT CAN BE
CONTAINED IN A 32 BIT VARIABLE

DO :1 <- #1
DO :2 <- #1
PLEASE :4 <- #1
DO READ OUT :1 + :2
DO (1) NEXT
(1) PLEASE DO (1509) NEXT
PLEASE (3) NEXT
PLEASE FORGET #1
DO :1 <- :2
PLEASE DO :2 <- :3
DO READ OUT :2
(2) DO (1) NEXT
PLEASE GIVE UP
(3) DO RESUME :4